export const demoDoctors = [
  {
    email: 'dr.lina.hassan@babytracker.com',
    password: 'Demo123!',
    first_name: 'Lina',
    last_name: 'Hassan',
    phone_number: '+201001110001',
    whatsapp: '+201001110001',
    bio: 'Pediatrician focused on newborn care, vaccination planning, and early growth monitoring.',
    rating: 4.9,
    role: 'Doctor',
    specialization: 'Pediatrics',
    license_number: 'PED-10421',
    verified: true,
    image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Doctor%20Ray%20IMG%206914.JPG',
    appointments: [
      { available_day: 'Sunday', start_time: '09:00', end_time: '12:00' },
      { available_day: 'Tuesday', start_time: '13:00', end_time: '16:00' },
      { available_day: 'Thursday', start_time: '10:00', end_time: '13:00' },
    ],
  },
  {
    email: 'dr.omer.farid@babytracker.com',
    password: 'Demo123!',
    first_name: 'Omer',
    last_name: 'Farid',
    phone_number: '+201001110002',
    whatsapp: '+201001110002',
    bio: 'General medicine doctor who helps parents with fever management, mild infections, and follow-up care.',
    rating: 4.7,
    role: 'Doctor',
    specialization: 'General Medicine',
    license_number: 'GEN-22014',
    verified: true,
    image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Doctor%20J.%20Chambers%20Wellcome%20M0002607.jpg',
    appointments: [
      { available_day: 'Monday', start_time: '11:00', end_time: '14:00' },
      { available_day: 'Wednesday', start_time: '14:00', end_time: '17:00' },
      { available_day: 'Saturday', start_time: '09:30', end_time: '12:30' },
    ],
  },
  {
    email: 'dr.sara.amin@babytracker.com',
    password: 'Demo123!',
    first_name: 'Sara',
    last_name: 'Amin',
    phone_number: '+201001110003',
    whatsapp: '+201001110003',
    bio: 'Child nutrition specialist who supports feeding plans, healthy weight gain, and vitamin guidance.',
    rating: 4.8,
    role: 'Doctor',
    specialization: 'Pediatric Nutrition',
    license_number: 'NUT-99211',
    verified: true,
    image_url: 'https://iiif.nlm.nih.gov/iiif/2/nlm:nlmuid-101425721-img/full/full/0/default.jpg',
    appointments: [
      { available_day: 'Sunday', start_time: '15:00', end_time: '18:00' },
      { available_day: 'Tuesday', start_time: '09:00', end_time: '12:00' },
      { available_day: 'Friday', start_time: '10:00', end_time: '13:00' },
    ],
  },
];

export const demoDoses = [
  {
    dose_name: 'Newborn Dose',
    recommended_age: 0,
    description: 'First newborn protection dose given in the earliest days after birth.',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pravaz%20syringe%20Wellcome%20L0033875.jpg',
  },
  {
    dose_name: '2-Month Dose',
    recommended_age: 2,
    description: 'Routine two-month vaccination window for the first major protection cycle.',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Vaccine%20Vial%20(NIH%20BioArt%20535%20-%20636854).svg',
  },
  {
    dose_name: '4-Month Dose',
    recommended_age: 4,
    description: 'Follow-up dose to strengthen immune response and keep protection active.',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Flu%20vaccine%20vial%20(2021)%20A.jpg',
  },
  {
    dose_name: '6-Month Dose',
    recommended_age: 6,
    description: 'Six-month vaccine window for continuing the infant immunization plan.',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pravaz%20syringe%20Wellcome%20L0033875.jpg',
  },
  {
    dose_name: '9-Month Dose',
    recommended_age: 9,
    description: 'Important checkpoint dose for babies approaching the first year.',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Vaccine%20Vial%20(NIH%20BioArt%20535%20-%20636854).svg',
  },
  {
    dose_name: '12-Month Booster',
    recommended_age: 12,
    description: 'One-year booster to close the first year vaccination cycle.',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Flu%20vaccine%20vial%20(2021)%20A.jpg',
  },
];

export const demoVaccines = [
  {
    vaccine_name: 'BCG Vaccine',
    description: 'Protects against severe forms of tuberculosis in early infancy.',
    min_age: 0,
    max_age: 1,
    doses_required: 1,
    is_mandatory: true,
    dose_name: 'Newborn Dose',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Vaccine%20Vial%20(NIH%20BioArt%20535%20-%20636854).svg',
  },
  {
    vaccine_name: 'Hepatitis B Vaccine',
    description: 'Early hepatitis B protection for newborns and infants.',
    min_age: 0,
    max_age: 18,
    doses_required: 3,
    is_mandatory: true,
    dose_name: 'Newborn Dose',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Flu%20vaccine%20vial%20(2021)%20A.jpg',
  },
  {
    vaccine_name: 'Pentavalent Vaccine',
    description: 'Combination vaccine for diphtheria, tetanus, pertussis, hepatitis B, and Hib.',
    min_age: 2,
    max_age: 6,
    doses_required: 3,
    is_mandatory: true,
    dose_name: '2-Month Dose',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pravaz%20syringe%20Wellcome%20L0033875.jpg',
  },
  {
    vaccine_name: 'Rotavirus Vaccine',
    description: 'Helps protect babies against severe diarrhea caused by rotavirus.',
    min_age: 2,
    max_age: 8,
    doses_required: 2,
    is_mandatory: false,
    dose_name: '2-Month Dose',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Vaccine%20Vial%20(NIH%20BioArt%20535%20-%20636854).svg',
  },
  {
    vaccine_name: 'MMR Vaccine',
    description: 'Combined protection against measles, mumps, and rubella.',
    min_age: 12,
    max_age: 18,
    doses_required: 2,
    is_mandatory: false,
    dose_name: '12-Month Booster',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Flu%20vaccine%20vial%20(2021)%20A.jpg',
  },
  {
    vaccine_name: 'Influenza Vaccine',
    description: 'Seasonal flu protection for eligible children after the age of six months.',
    min_age: 6,
    max_age: 60,
    doses_required: 2,
    is_mandatory: false,
    dose_name: '6-Month Dose',
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pravaz%20syringe%20Wellcome%20L0033875.jpg',
  },
];

export const demoMedicines = [
  {
    name: 'Paracetamol Suspension',
    description: 'Used for fever and mild pain relief in children when prescribed appropriately.',
    dosage: '5ml every 6-8 hours as needed',
    manufacturer: 'BabyCare Pharma',
    price: 38,
    category: 'Pediatrics',
    prescriptionRequired: false,
    sideEffects: ['Nausea', 'Rash', 'Liver risk if overdosed'],
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/A%20collection%20of%20generic%20medicine%20pills%20on%20a%20white%20background.jpg',
  },
  {
    name: 'Oral Rehydration Salts',
    description: 'Helps replace fluids and minerals during dehydration or mild diarrhea.',
    dosage: 'Mix one sachet with clean water',
    manufacturer: 'Health First',
    price: 22,
    category: 'Digestive',
    prescriptionRequired: false,
    sideEffects: ['Bloating', 'Mild nausea'],
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Medicine%20Drug%20Pills%20on%20Plate.png',
  },
  {
    name: 'Vitamin D3 Drops',
    description: 'Supports healthy bone development and calcium absorption for infants.',
    dosage: 'As directed by pediatrician',
    manufacturer: 'Sunny Labs',
    price: 55,
    category: 'Vitamins',
    prescriptionRequired: false,
    sideEffects: ['Rare stomach upset'],
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pharmacy-bottle-11.jpg',
  },
  {
    name: 'Saline Nasal Drops',
    description: 'Gentle saline solution for blocked noses and everyday congestion relief.',
    dosage: '1-2 drops in each nostril as needed',
    manufacturer: 'CarePlus',
    price: 18,
    category: 'Respiratory',
    prescriptionRequired: false,
    sideEffects: ['Temporary irritation'],
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Apothecarybottles.jpg',
  },
  {
    name: 'Zinc Syrup',
    description: 'Supports immunity and is often used in short pediatric recovery plans.',
    dosage: 'As directed by doctor',
    manufacturer: 'MediKids',
    price: 30,
    category: 'Vitamins',
    prescriptionRequired: false,
    sideEffects: ['Metallic taste', 'Mild stomach discomfort'],
    image: 'https://commons.wikimedia.org/wiki/Special:FilePath/Pharmacy-bottle-11.jpg',
  },
];

export const demoArticles = [
  {
    title: 'How to prepare for your baby vaccination day',
    content:
      'Keep the vaccine card ready, feed the baby before the visit, dress the child in comfortable clothes, and keep a favorite toy to reduce stress during the appointment.',
    author: 'Dr. Lina Hassan',
    publicationDate: '2026-05-10',
    tags: ['vaccination', 'baby care', 'tips'],
    category: 'Baby Care',
    status: 'published',
    views: 124,
    references: ['https://www.who.int/'],
    isFeatured: true,
    image: null,
  },
  {
    title: 'Common mild side effects after vaccines',
    content:
      'Mild fever, a sore arm, or short-term irritability can happen after vaccines. These symptoms usually improve quickly with rest and hydration.',
    author: 'Dr. Omer Farid',
    publicationDate: '2026-05-12',
    tags: ['vaccines', 'side effects'],
    category: 'Vaccines',
    status: 'published',
    views: 98,
    references: ['https://www.cdc.gov/'],
    isFeatured: true,
    image: null,
  },
  {
    title: 'When baby fever needs a doctor',
    content:
      'A fever that lasts too long, affects feeding, or comes with unusual drowsiness should be reviewed by a doctor quickly. Trust your instinct when the child looks unwell.',
    author: 'Dr. Sara Amin',
    publicationDate: '2026-05-14',
    tags: ['fever', 'doctor advice', 'baby health'],
    category: 'Health Tips',
    status: 'published',
    views: 76,
    references: ['https://www.nhs.uk/'],
    isFeatured: false,
    image: null,
  },
  {
    title: 'Hydration tips for infants and toddlers',
    content:
      'Offer fluids regularly, monitor wet diapers, and use age-appropriate feeding strategies to keep your child hydrated, especially during hot weather.',
    author: 'Dr. Lina Hassan',
    publicationDate: '2026-05-16',
    tags: ['hydration', 'nutrition', 'parenting'],
    category: 'Nutrition',
    status: 'published',
    views: 85,
    references: ['https://www.healthline.com/'],
    isFeatured: false,
    image: null,
  },
];

export const demoParent = {
  email: 'demo.parent@babytracker.com',
  password: 'Demo123!',
  first_name: 'Mona',
  last_name: 'Ali',
  phone_number: '+201011223344',
  role: 'user',
  verified: true,
};

export const demoChild = {
  first_name: 'Adam',
  last_name: 'Ali',
  gender: 'Male',
  date_of_birth: '2023-06-18',
  weight: 12.1,
  height: 86,
};
